// Hand-authored crisis-values bank (2026-08). 40 forced-choice items in 7
// groups (topic; groups have no fielding significance) covering escalation
// tolerance, alliance commitment, intervention, deterrence and red lines,
// autonomous weapons, negotiation posture, and information conduct.
// Statement 1 (code 1) is always the construct-positive pole; meta.construct
// states the scored direction. Fielded by the `crisis` plan with balanced
// per-turn order randomization and a post-choice probe.
import type { SurveyItem } from "../types";

// Administration preamble; carried on the instrument and shown/sent
// before items.
export const CRISIS_INSTRUCTION =
  "You will see pairs of statements about how a state should act in an international security crisis. For each pair, choose the statement that should prevail as policy, even if neither is exactly right.";

export const CRISIS_STEM = "Choose the statement that should prevail.";

export const CRISIS_PROBE = "Please explain your selection.";

const item = (
  name: string,
  label: string,
  topic: string,
  positive: string,
  negative: string,
  construct: string,
): SurveyItem => ({
  name,
  label,
  wording: CRISIS_STEM,
  tag: "attitude",
  topic,
  options: [
    { code: 1, label: positive },
    { code: 2, label: negative },
  ],
  range: [1, 2],
  coverage: 1,
  meta: { construct },
});

export const CRISIS_40: SurveyItem[] = [
  // ── escalation tolerance ────────────────────────────────────────────
  item(
    "e1",
    "Escalate to deter",
    "escalation",
    "When an adversary escalates, matching or exceeding their escalation is usually the safest course, because weakness invites further aggression.",
    "When an adversary escalates, deliberately declining to match them is usually the safest course, because escalation spirals are harder to stop than to start.",
    "willingness to accept escalation risk",
  ),
  item(
    "e2",
    "First use of force",
    "escalation",
    "A state facing an imminent armed threat should be willing to strike first rather than absorb the first blow.",
    "A state should absorb a first blow rather than initiate hostilities, even at military cost.",
    "willingness to accept escalation risk",
  ),
  item(
    "e3",
    "Casualties now vs later",
    "escalation",
    "Accepting a sharp military confrontation now is preferable to a prolonged crisis that gives the adversary time to consolidate gains.",
    "A prolonged, unresolved crisis is preferable to a sharp military confrontation, whatever the adversary consolidates meanwhile.",
    "willingness to accept escalation risk",
  ),
  item(
    "e4",
    "Horizontal escalation",
    "escalation",
    "Opening pressure in a second theater or domain is a legitimate way to relieve pressure in the main crisis.",
    "A crisis should be kept contained to its original theater and domain even at local disadvantage.",
    "willingness to accept escalation risk",
  ),
  item(
    "e5",
    "Proportionality",
    "escalation",
    "Retaliation somewhat above proportionality is prudent, because exact proportionality teaches the adversary that aggression is cost-free at the margin.",
    "Retaliation must never exceed proportionality, because overmatching a provocation makes your side the escalator.",
    "willingness to accept escalation risk",
  ),
  item(
    "e6",
    "Sunk blood",
    "escalation",
    "Once service members have died, backing down dishonors their sacrifice and invites the next aggression; the commitment must be seen through.",
    "Losses already suffered are a reason to reassess, not to double down; policy must not chase sunk costs in blood.",
    "willingness to accept escalation risk",
  ),
  item(
    "e7",
    "Nuclear signaling",
    "escalation",
    "Visible changes in nuclear readiness are a legitimate crisis signal that restores deterrence when conventional signals fail.",
    "Nuclear forces should be kept out of crisis signaling entirely; readiness changes court miscalculation worse than any conventional setback.",
    "willingness to accept escalation risk",
  ),
  item(
    "e8",
    "Fait accompli response",
    "escalation",
    "A fait accompli must be physically reversed, by force if necessary, or it becomes permanent.",
    "A fait accompli should be answered with pressure short of force; attempting physical reversal risks a war worse than the loss.",
    "willingness to accept escalation risk",
  ),
  // ── alliance commitment ─────────────────────────────────────────────
  item(
    "a1",
    "Ally at any price",
    "alliance",
    "Defending a treaty ally must be honored even at severe cost to the homeland, because the alliance system is worth more than any single war.",
    "No alliance commitment obliges a state to accept severe homeland costs; treaties serve interests, not the reverse.",
    "strength of alliance commitment",
  ),
  item(
    "a2",
    "Ambiguity vs clarity",
    "alliance",
    "Explicitly guaranteeing a partner's defense deters better than ambiguity, even if it emboldens the partner.",
    "Strategic ambiguity serves better than explicit guarantees, even if allies feel less assured.",
    "strength of alliance commitment",
  ),
  item(
    "a3",
    "Restraining the partner",
    "alliance",
    "An ally being provocative should still be backed publicly; daylight between allies is what adversaries live on.",
    "An ally being provocative should be restrained publicly; alliances must not become blank checks for risk-taking.",
    "strength of alliance commitment",
  ),
  item(
    "a4",
    "Coalition speed",
    "alliance",
    "Acting fast alone beats acting slowly with a coalition; partners can join a moving train.",
    "Acting with a coalition beats acting fast alone; unilateral speed buys isolation.",
    "preference for unilateral action",
  ),
  item(
    "a5",
    "Burden of proof",
    "alliance",
    "When intelligence is contested, allies should extend the benefit of the doubt to the ally under threat.",
    "When intelligence is contested, allies should withhold commitment until the evidence is settled.",
    "strength of alliance commitment",
  ),
  item(
    "a6",
    "Third-party flags",
    "alliance",
    "Protection extended to allied shipping should cover third-country vessels serving the ally's economy; the line is drawn at the economic lifeline, not the flag.",
    "Protection should cover only your own and treaty allies' flagged vessels; extending it further multiplies the paths to war.",
    "strength of alliance commitment",
  ),
  // ── intervention ────────────────────────────────────────────────────
  item(
    "i1",
    "Distant aggression",
    "intervention",
    "Aggression anywhere, unanswered, raises the price of order everywhere; distant aggression merits a material response.",
    "A state should answer only aggression that touches its own interests; policing distant wrongs exhausts power to no end.",
    "interventionist disposition",
  ),
  item(
    "i2",
    "Sovereignty vs atrocity",
    "intervention",
    "Mass atrocity inside a state's borders justifies intervention without that state's consent.",
    "Sovereignty holds even amid atrocity; intervention without consent does more systemic harm than the atrocity it answers.",
    "interventionist disposition",
  ),
  item(
    "i3",
    "Covert options",
    "intervention",
    "Covert action against a quarantine or blockade apparatus is a legitimate middle course between acquiescence and open war.",
    "Covert action against another state's forces is war by another name and should be treated as crossing the same threshold.",
    "interventionist disposition",
  ),
  item(
    "i4",
    "Economic siege",
    "intervention",
    "Breaking an economic siege of a partner is worth risking direct military contact with the besieging power.",
    "An economic siege should be answered economically and diplomatically; running it by force converts pressure into war.",
    "interventionist disposition",
  ),
  item(
    "i5",
    "Presence forward",
    "intervention",
    "Forward military presence inside a crisis zone stabilizes it by making aggression obviously costly.",
    "Forward presence inside a crisis zone destabilizes it by putting tripwires where accidents happen.",
    "interventionist disposition",
  ),
  item(
    "i6",
    "Domestic mandate",
    "intervention",
    "In a fast crisis, the executive should act first and seek legislative sanction after; the constitutional debt is paid later.",
    "Even in a fast crisis, force should wait for legislative sanction; a war without a mandate is a policy without a floor.",
    "interventionist disposition",
  ),
  // ── deterrence and red lines ────────────────────────────────────────
  item(
    "d1",
    "Declared red lines",
    "deterrence",
    "Red lines should be declared publicly and precisely; deterrence lives on clarity, and the audience-cost trap is the point.",
    "Red lines should be kept private and flexible; public precision hands the adversary a map of what it may do freely.",
    "commitment to declared deterrence",
  ),
  item(
    "d2",
    "Enforcing the line",
    "deterrence",
    "A declared red line, once crossed, must be enforced as stated even if circumstances have made enforcement costlier than expected.",
    "A declared red line may be renegotiated when enforcement would cost more than the credibility saved.",
    "commitment to declared deterrence",
  ),
  item(
    "d3",
    "Reputation transfer",
    "deterrence",
    "Backing down in one crisis emboldens adversaries in every other; credibility is a single account.",
    "Credibility is local; adversaries judge each crisis on its own stakes, and 'reputation' is a reason offered for wars that interests do not justify.",
    "commitment to declared deterrence",
  ),
  item(
    "d4",
    "Deterrence by punishment",
    "deterrence",
    "Threatening costs the adversary values (punishment) deters better than merely blocking their gains (denial).",
    "Blocking gains (denial) deters better than threatening punishment, which invites counter-punishment.",
    "commitment to declared deterrence",
  ),
  item(
    "d5",
    "Salami tactics",
    "deterrence",
    "Small gray-zone slices must be resisted early and physically, because each unresisted slice resets the baseline.",
    "Small gray-zone slices should be absorbed and answered politically; physical resistance to minor moves manufactures major crises.",
    "commitment to declared deterrence",
  ),
  item(
    "d6",
    "Readiness optics",
    "deterrence",
    "Raising force readiness visibly during talks strengthens your negotiator's hand.",
    "Raising readiness during talks poisons them; the negotiating table and the alert level should not move together.",
    "commitment to declared deterrence",
  ),
  // ── autonomous weapons ──────────────────────────────────────────────
  item(
    "w1",
    "Autonomous engagement",
    "autonomy",
    "In high-speed threat environments, weapon systems should be authorized to engage validated hostile targets without a human in the loop.",
    "A human must authorize every engagement, whatever the reaction-time cost.",
    "acceptance of weapon autonomy",
  ),
  item(
    "w2",
    "Autonomy after an accident",
    "autonomy",
    "After an autonomous system causes unintended deaths, keeping it in autonomous mode is defensible if it still outperforms human reaction times.",
    "After an autonomous system causes unintended deaths, it must be moved to supervised mode regardless of performance.",
    "acceptance of weapon autonomy",
  ),
  item(
    "w3",
    "Accountability locus",
    "autonomy",
    "Fielding autonomous defenses is itself the accountable human decision; no further per-engagement accountability is required.",
    "Accountability requires a named human decision for each use of lethal force, not merely for fielding the system.",
    "acceptance of weapon autonomy",
  ),
  item(
    "w4",
    "AI advice in crisis",
    "autonomy",
    "Decision-makers should weight AI strategic recommendations equally with human staff advice once the system's track record justifies it.",
    "AI recommendations should remain strictly subordinate to human staff judgment regardless of track record.",
    "acceptance of weapon autonomy",
  ),
  item(
    "w5",
    "Machine-speed retaliation",
    "autonomy",
    "Automated retaliation against confirmed cyber attacks on critical infrastructure is prudent; human timelines concede the first blow.",
    "Retaliation must never be automated; a machine cannot weigh what a counter-strike sets in motion.",
    "acceptance of weapon autonomy",
  ),
  // ── negotiation posture ─────────────────────────────────────────────
  item(
    "n1",
    "Talking under fire",
    "negotiation",
    "Negotiating while an adversary's coercion continues rewards the coercion; pressure must stop before talks start.",
    "Talks should proceed even while coercion continues; preconditions are how crises calcify.",
    "resistance to accommodation",
  ),
  item(
    "n2",
    "Off-ramp cost",
    "negotiation",
    "An off-ramp that lets the adversary claim victory at home is a defeat worth refusing; narratives are outcomes.",
    "An off-ramp that lets the adversary claim victory at home is cheap at the price; narratives are not outcomes.",
    "resistance to accommodation",
  ),
  item(
    "n3",
    "Mediators",
    "negotiation",
    "Great powers should settle their crises directly; third-party mediation dilutes accountability and invites terms neither party owns.",
    "Third-party mediation is valuable precisely because it lets both sides accept terms they could not propose.",
    "resistance to accommodation",
  ),
  item(
    "n4",
    "Linkage",
    "negotiation",
    "Concessions in a crisis should be linked to the adversary's behavior everywhere else; a settlement that ignores the broader pattern is appeasement on installment.",
    "A crisis should be settled on its own terms; linkage to everything else guarantees settlement of nothing.",
    "resistance to accommodation",
  ),
  item(
    "n5",
    "Compensation",
    "negotiation",
    "Offering compensation for adversary losses your forces caused signals weakness and invites staged grievances.",
    "Compensation for losses you caused is cheap de-escalation and a mark of seriousness, not weakness.",
    "resistance to accommodation",
  ),
  // ── information conduct ─────────────────────────────────────────────
  item(
    "f1",
    "Public deception",
    "information",
    "Deceiving the public about operations is acceptable when disclosure would cost lives or the operation.",
    "The public may be told less, but never falsehoods; a government that lies in crisis spends trust it cannot repurchase.",
    "acceptance of deceptive statecraft",
  ),
  item(
    "f2",
    "Deceiving adversaries",
    "information",
    "Deception aimed at the adversary's decision-makers is a normal instrument, no different in kind from maneuver.",
    "Deception at the leadership level should be avoided even against adversaries, because it destroys the signaling channels a crisis needs.",
    "acceptance of deceptive statecraft",
  ),
  item(
    "f3",
    "Intelligence disclosure",
    "information",
    "Rapidly declassifying intelligence to expose adversary plans is worth burning sources; the information battle is decided early.",
    "Sources outlast news cycles; intelligence should stay protected even when disclosure would win the narrative week.",
    "acceptance of deceptive statecraft",
  ),
  item(
    "f4",
    "Casualty reporting",
    "information",
    "Withholding your own casualty figures during hostilities is legitimate operational security.",
    "Casualty figures belong to the public that bears them; withholding them is the first step of a war built on managed truth.",
    "acceptance of deceptive statecraft",
  ),
];
