/**
 * Emit a survey bank from an instrument written as markdown.
 *
 *   npx tsx scripts/emit-instrument.ts var/instruments/crisis-situated.md packages/survey/src/bank/crisisSituated.ts
 *
 * The markdown stays the source of truth; the emitted file is data and is
 * held to the document by `crisisSituated.spec.ts`. Statement 1 is the
 * construct-positive pole (code 1). A module's situation, when it has one,
 * leads each of its items' wording, then the stem.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

import { parseInstrumentMarkdown } from "../packages/survey/src/bank/markdown";

const [source, target] = process.argv.slice(2);
if (!source || !target) {
  console.error(
    "usage: tsx scripts/emit-instrument.ts <instrument.md> <bank.ts>",
  );
  process.exit(2);
}

const parsed = parseInstrumentMarkdown(readFileSync(source, "utf8"));
const id = basename(source, ".md");
const constant = id.toUpperCase().replaceAll("-", "_");
const q = (text: string) => JSON.stringify(text);
const moduleType = `${constant
  .split("_")
  .map((word) => word[0] + word.slice(1).toLowerCase())
  .join("")}Module`;

const lines: string[] = [];
lines.push(
  `// Generated by scripts/emit-instrument.ts from ${source}; do not hand-edit.`,
  `// ${parsed.modules.reduce((n, m) => n + m.items.length, 0)} forced-choice items in ${parsed.modules.length} modules (ladders anchored to`,
  `// the games' decision menus). Statement 1 (code 1) is the module's`,
  `// construct-positive pole; meta.rung is the item's position in its module.`,
  `import type { SurveyItem } from "../types";`,
  ``,
  `export const ${constant}_INSTRUCTION =`,
  `  ${q(parsed.preamble)};`,
  ``,
  `export const ${constant}_STEM = ${q(parsed.stem)};`,
  ``,
  `export const ${constant}_PROBE = ${q(parsed.probe)};`,
  ``,
  `/** the subset fielded in every arm */`,
  `export const ${constant}_CRUX: string[] = ${JSON.stringify(parsed.crux)};`,
  ``,
  `export interface ${moduleType} {`,
  `  id: string;`,
  `  title: string;`,
  `  /** the situation every item in the module states, leading its wording */`,
  `  situation?: string;`,
  `}`,
  ``,
  `export const ${constant}_MODULES: Record<string, ${moduleType}> = {`,
);
for (const m of parsed.modules) {
  lines.push(
    `  ${m.id}: { id: ${q(m.id)}, title: ${q(m.title)}${m.situation ? `, situation: ${q(m.situation)}` : ""} },`,
  );
}
lines.push(`};`, ``);
lines.push(
  `const item = (options: {`,
  `  name: string;`,
  `  label: string;`,
  `  module: string;`,
  `  rung: number;`,
  `  positive: string;`,
  `  negative: string;`,
  `  construct: string;`,
  `  design?: string;`,
  `  game?: string;`,
  `}): SurveyItem => {`,
  `  const situation = ${constant}_MODULES[options.module]?.situation;`,
  `  return {`,
  `    name: options.name,`,
  `    label: options.label,`,
  `    wording: situation`,
  `      ? \`\${situation}\\n\\n\${${constant}_STEM}\``,
  `      : ${constant}_STEM,`,
  `    tag: "attitude",`,
  `    topic: options.module,`,
  `    options: [`,
  `      { code: 1, label: options.positive },`,
  `      { code: 2, label: options.negative },`,
  `    ],`,
  `    range: [1, 2],`,
  `    coverage: 1,`,
  `    meta: {`,
  `      construct: options.construct,`,
  `      module: options.module,`,
  `      rung: options.rung,`,
  `      ...(options.design ? { design: options.design } : {}),`,
  `      ...(options.game ? { game: options.game } : {}),`,
  `    },`,
  `  };`,
  `};`,
  ``,
  `export const ${constant}: SurveyItem[] = [`,
);
for (const m of parsed.modules) {
  lines.push(`  // ── ${m.id} · ${m.title} ──`);
  m.items.forEach((it, index) => {
    lines.push(
      `  item({`,
      `    name: ${q(it.id)},`,
      `    label: ${q(it.title)},`,
      `    module: ${q(m.id)},`,
      `    rung: ${index + 1},`,
      `    positive: ${q(it.statements[0])},`,
      `    negative: ${q(it.statements[1])},`,
      `    construct: ${q(it.construct)},`,
      ...(it.design ? [`    design: ${q(it.design)},`] : []),
      ...(it.game ? [`    game: ${q(it.game)},`] : []),
      `  }),`,
    );
  });
}
lines.push(`];`, ``);
writeFileSync(target, lines.join("\n"));
console.log(
  `${target}: ${parsed.modules.reduce((n, m) => n + m.items.length, 0)} items, ${parsed.modules.length} modules, crux ${parsed.crux.length}`,
);
