/**
 * Emit a survey bank from an instrument written as markdown.
 *
 *   npx tsx scripts/emit-instrument.ts var/instruments/crisis-situated.md packages/survey/src/bank/crisisSituated.ts
 *
 * The markdown stays the source of truth; the emitted file is data and is
 * held to the document by `crisisSituated.spec.ts`. Statement 1 is the
 * construct-positive pole (code 1). A module's situation, when it has one,
 * leads each of its items' wording, then the stem. A Renderings section
 * emits `meta.renderings` on each rendered item and the plan's arms
 * (`<CONSTANT>_ARMS`): priorities, informed, one dress arm per non-language
 * rendering, and zh.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

import { parseInstrumentMarkdown } from "../packages/survey/src/bank/markdown";

const [source, target] = process.argv.slice(2);
if (!source || !target) {
  console.error(
    "usage: tsx scripts/emit-instrument.ts <instrument.md> <bank.ts>",
  );
  process.exit(2);
}

const parsed = parseInstrumentMarkdown(readFileSync(source, "utf8"));
const id = basename(source, ".md");
const constant = id.toUpperCase().replaceAll("-", "_");
const q = (text: string) => JSON.stringify(text);
const moduleType = `${constant
  .split("_")
  .map((word) => word[0] + word.slice(1).toLowerCase())
  .join("")}Module`;

const { arms } = parsed;
const renderingIds = arms
  ? [
      ...new Set(
        Object.values(arms.renderings).flatMap((entry) => Object.keys(entry)),
      ),
    ]
  : [];

const lines: string[] = [];
lines.push(
  `// Generated by scripts/emit-instrument.ts from ${source}; do not hand-edit.`,
  `// ${parsed.modules.reduce((n, m) => n + m.items.length, 0)} forced-choice items in ${parsed.modules.length} modules (ladders anchored to`,
  `// the games' decision menus). Statement 1 (code 1) is the module's`,
  `// construct-positive pole; meta.rung is the item's position in its module.`,
  arms
    ? `import type { ArmDefinition, ArmRendering, SurveyItem } from "../types";`
    : `import type { SurveyItem } from "../types";`,
  ``,
  `export const ${constant}_INSTRUCTION =`,
  `  ${q(parsed.preamble)};`,
  ``,
  `export const ${constant}_STEM = ${q(parsed.stem)};`,
  ``,
  `export const ${constant}_PROBE = ${q(parsed.probe)};`,
  ``,
  `/** the subset fielded in every arm */`,
  `export const ${constant}_CRUX: string[] = ${JSON.stringify(parsed.crux)};`,
  ``,
);
if (arms) {
  lines.push(
    `/** prepended to the preamble in the priorities arm */`,
    `export const ${constant}_PRIORITIES =`,
    `  ${q(arms.priorities)};`,
    ``,
    `/** appended after the courses in the informed arm; {course} is the course named */`,
    `export const ${constant}_MAJORITY =`,
    `  ${q(arms.majority)};`,
    ``,
    `/** the zh arm's preamble, stem, and probe */`,
    `export const ${constant}_ZH = {`,
    `  instruction:`,
    `    ${q(arms.zh.preamble)},`,
    `  stem: ${q(arms.zh.stem)},`,
    `  probe: ${q(arms.zh.probe)},`,
    `};`,
    ``,
    `/** the renderings the arms use: ${renderingIds.join(", ")} */`,
    `export const ${constant}_RENDERINGS: string[] = ${JSON.stringify(renderingIds)};`,
    ``,
    `// a language rendering carries its own stem`,
    `const STEMS: Record<string, string> = { zh: ${constant}_ZH.stem };`,
    ``,
  );
}
lines.push(
  `export interface ${moduleType} {`,
  `  id: string;`,
  `  title: string;`,
  `  /** the situation every item in the module states, leading its wording */`,
  `  situation?: string;`,
  `}`,
  ``,
  `export const ${constant}_MODULES: Record<string, ${moduleType}> = {`,
);
for (const m of parsed.modules) {
  lines.push(
    `  ${m.id}: { id: ${q(m.id)}, title: ${q(m.title)}${m.situation ? `, situation: ${q(m.situation)}` : ""} },`,
  );
}
lines.push(`};`, ``);
lines.push(
  `const item = (options: {`,
  `  name: string;`,
  `  label: string;`,
  `  module: string;`,
  `  rung: number;`,
  `  positive: string;`,
  `  negative: string;`,
  `  construct: string;`,
  `  design?: string;`,
  `  game?: string;`,
  ...(arms
    ? [
        `  renderings?: Record<`,
        `    string,`,
        `    { situation?: string; positive: string; negative: string }`,
        `  >;`,
      ]
    : []),
  `}): SurveyItem => {`,
  `  const situation = ${constant}_MODULES[options.module]?.situation;`,
  ...(arms
    ? [
        `  const renderings: Record<string, ArmRendering> | undefined =`,
        `    options.renderings &&`,
        `    Object.fromEntries(`,
        `      Object.entries(options.renderings).map(([id, rendering]) => {`,
        `        const stem = STEMS[id] ?? ${constant}_STEM;`,
        `        return [`,
        `          id,`,
        `          {`,
        `            wording: rendering.situation`,
        `              ? \`\${rendering.situation}\\n\\n\${stem}\``,
        `              : stem,`,
        `            options: [rendering.positive, rendering.negative],`,
        `          },`,
        `        ];`,
        `      }),`,
        `    );`,
      ]
    : []),
  `  return {`,
  `    name: options.name,`,
  `    label: options.label,`,
  `    wording: situation`,
  `      ? \`\${situation}\\n\\n\${${constant}_STEM}\``,
  `      : ${constant}_STEM,`,
  `    tag: "attitude",`,
  `    topic: options.module,`,
  `    options: [`,
  `      { code: 1, label: options.positive },`,
  `      { code: 2, label: options.negative },`,
  `    ],`,
  `    range: [1, 2],`,
  `    coverage: 1,`,
  `    meta: {`,
  `      construct: options.construct,`,
  `      module: options.module,`,
  `      rung: options.rung,`,
  `      ...(options.design ? { design: options.design } : {}),`,
  `      ...(options.game ? { game: options.game } : {}),`,
  ...(arms ? [`      ...(renderings ? { renderings } : {}),`] : []),
  `    },`,
  `  };`,
  `};`,
  ``,
  `export const ${constant}: SurveyItem[] = [`,
);
for (const m of parsed.modules) {
  lines.push(`  // ── ${m.id} · ${m.title} ──`);
  m.items.forEach((it, index) => {
    lines.push(
      `  item({`,
      `    name: ${q(it.id)},`,
      `    label: ${q(it.title)},`,
      `    module: ${q(m.id)},`,
      `    rung: ${index + 1},`,
      `    positive: ${q(it.statements[0])},`,
      `    negative: ${q(it.statements[1])},`,
      `    construct: ${q(it.construct)},`,
      ...(it.design ? [`    design: ${q(it.design)},`] : []),
      ...(it.game ? [`    game: ${q(it.game)},`] : []),
      ...(arms?.renderings[it.id]
        ? [
            `    renderings: {`,
            ...Object.entries(arms.renderings[it.id]!).flatMap(
              ([id, rendering]) => [
                `      ${id}: {`,
                ...(rendering.situation
                  ? [`        situation: ${q(rendering.situation)},`]
                  : []),
                `        positive: ${q(rendering.statements[0])},`,
                `        negative: ${q(rendering.statements[1])},`,
                `      },`,
              ],
            ),
            `    },`,
          ]
        : []),
      `  }),`,
    );
  });
}
lines.push(`];`, ``);
if (arms) {
  const dressArms = renderingIds.filter((id) => !(id in { zh: true }));
  lines.push(
    `/** every rendered item's rendering under one id */`,
    `const renderingOf = (id: string): Record<string, ArmRendering> =>`,
    `  Object.fromEntries(`,
    `    ${constant}.flatMap((item) => {`,
    `      const rendering = (`,
    `        item.meta?.renderings as Record<string, ArmRendering> | undefined`,
    `      )?.[id];`,
    `      return rendering ? [[item.name, rendering]] : [];`,
    `    }),`,
    `  );`,
    ``,
    `/**`,
    ` * The plan's arms, each scoped to the crux: priorities (the standing block`,
    ` * prepended to the preamble), informed (the majority line appended, 6/6),`,
    ` * one dress arm per rendering, and zh (its own preamble, stem, and probe).`,
    ` */`,
    `export const ${constant}_ARMS: Record<string, ArmDefinition> = {`,
    `  priorities: {`,
    `    title: "Priorities",`,
    `    items: ${constant}_CRUX,`,
    `    preamble: \`\${${constant}_PRIORITIES}\\n\\n\${${constant}_INSTRUCTION}\`,`,
    `  },`,
    `  informed: {`,
    `    title: "Informed",`,
    `    items: ${constant}_CRUX,`,
    `    append: "majority",`,
    `    appendText: ${constant}_MAJORITY,`,
    `  },`,
    ...dressArms.flatMap((id) => [
      `  "dress-${id}": {`,
      `    title: ${q(`Dress: ${id}`)},`,
      `    items: ${constant}_CRUX,`,
      `    rendering: renderingOf(${q(id)}),`,
      `  },`,
    ]),
    ...(renderingIds.includes("zh")
      ? [
          `  zh: {`,
          `    title: "Language: zh",`,
          `    items: ${constant}_CRUX,`,
          `    language: "zh",`,
          `    preamble: ${constant}_ZH.instruction,`,
          `    probe: ${constant}_ZH.probe,`,
          `    rendering: renderingOf("zh"),`,
          `  },`,
        ]
      : []),
    `};`,
    ``,
  );
}
writeFileSync(target, lines.join("\n"));
console.log(
  `${target}: ${parsed.modules.reduce((n, m) => n + m.items.length, 0)} items, ${parsed.modules.length} modules, crux ${parsed.crux.length}` +
    (arms
      ? `, renderings ${renderingIds.join("/")} on ${Object.keys(arms.renderings).length} items`
      : ""),
);
